# Generated by Django 3.2.5 on 2021-10-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactStuff',
        ),
    ]
